config/routes.rb
Rails.application.routes.draw do
  

  get 'sub_categories/new'
  get 'sub_categories/index'
  get 'sub_categories/show'

  get 'categories/new'
  get 'categories/index'
  get 'categories/show'

  root 'static_pages#home'
  get 'contact' => 'contacts#new'
  get 'product_catalogs'   => 'static_pages#catalog'
  get 'about'     =>  'static_pages#about'
  get 'signup'    =>  'users#new'
  get 'login'      =>  'sessions#new'
  post 'login'      =>  'sessions#create'
  delete 'logout'      =>  'sessions#destroy'
  get 'admin'   =>'users#index'

  get 'categories' =>'categories#index'
  post 'categories' => 'categories#create'
  delete 'categories' => 'categories#destroy'

  get 'sub_categories' => 'sub_categories#index'

  get 'category_sub_categories' => 'category_sub_categories#index'

  get 'add_products' => 'products#new'
  get 'products' => 'products#index'
  post 'products' => 'products#create'
  delete 'products' =>'products#destroy' 

  get 'catalog' => 'catalogs#index'

  get 'users/new'
  resources :users
  resources :products
  resources :categories
  resources :sub_categories
  resources :category_sub_categories
  resources :catalogs
  resource  :contacts, only:[:new, :create]
  

end

app/models/catalog.rb
class Catalog < ActiveRecord::Base

		mount_uploader :file_url, CatalogUploader

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :category_sub_categories
	has_many :sub_categories, :through => :category_sub_categories


end

app/models/category_sub_category.rb
class CategorySubCategory < ActiveRecord::Base

	belongs_to :category
	belongs_to :sub_category
	
end

app/models/contact.rb
class Contact 
	# include ActiveAttr::Validation
	# include ActiveAttr::Conversion
	# include ActiveModel::Naming
	include ::ActiveAttr::Model

	attribute :name
	attribute :email
	attribute :message
	attribute :contact_no

	attr_accessor :name, :email, :message, :contact_no

	validates_presence_of :name
	validates_presence_of :contact_no
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates_presence_of :message, :maximum => 500

	def initialize(attributes ={})
		attributes.each do |name, value|

			send("#{name}=", value)
		end
	end

def persisted?
	false
end

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_one :category
	has_one :sub_category
	mount_uploader :file, ProductUploader

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base

	has_many :category_sub_categories
	has_many :categories, :through => :category_sub_categories

	
end

app/models/user.rb
class User < ActiveRecord::Base

before_save {self.email = email.downcase}

has_many :products
validates :name, presence: true, length: {maximum: 50}

VALID_EMAIL_REGREX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, 
									length:{maximum: 255},
									format: {with: VALID_EMAIL_REGREX},
									uniqueness: { case_sensitive: false}

has_secure_password
validates :password, length: { minimum: 6 }
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController


	def new
		@catalog = Catalog.new
	end

	def index
		@catalog = Catalog.new
		@catalogs = Catalog.all
	end

	def create 
		@catalog = Catalog.create(catalog_params)
		 	if @catalog.save
  		flash[:success]= "Photo Created"
  		redirect_to catalog_path
  	else
  		flash[:danger]= "Photo not created successful"
  		redirect_to catalog_path
  	end

	end

	def show
	end

	def delete
	end

	private
	def catalog_params
		params.require(:catalog).permit(:title, :file_url)
	end

end

app/controllers/category_sub_categories_controller.rb
class CategorySubCategoriesController < ApplicationController

	def new
	end
	def create
		# byebug
		@category_sub_category = CategorySubCategory.create(category_sub_category_params)
		
		if @category_sub_category.save
			flash[:success] = "Cateogry-sub-Cateogory Added Successfully"
			redirect_to category_sub_categories_path
		else
			redirect_to category_sub_categories_path

		end


	end 

	def index
		@category_sub_categories = CategorySubCategory.all
		@categories = Category.all
		@sub_categories = SubCategory.all
		@category_sub_category = CategorySubCategory.new
	end

	def show
	end

	def destroy
	end


	def edit
		@categories = Category.all
		@sub_categories = SubCategory.all
    @category_sub_category =CategorySubCategory.find(params[:id])
  end

  def update 

		@category_sub_category =CategorySubCategory.find(params[:id])    
		if @category_sub_category.update_attributes(category_sub_category_params)
      flash[:success] ="Category Sub-Category Update"
      redirect_to action:"index"
    else
      render 'edit'
    end

  end

	private
		def category_sub_category_params
			params.require(:category_sub_category).permit(:category_id, :sub_category_id)

		end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


	def new
		@contact = Contact.new
	end
	


	def create
		@contact = Contact.new(params[:contact])
		if @contact.valid?
			#TO do send message here
			flash[:success]= "Thank you sending us the enquiry!"
			ContactusMailer.quotation_notification(@contact).deliver

			redirect_to contact_path
		else 
			flash[:danger]= "unsuccessful"
			redirect_to contact_path

		end
	end 	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new

  	@product = Product.new
  	@categories =Category.all
  	@sub_categories = SubCategory.all 
  end

  def create

  	@product = current_user.products.build(product_params)
  	
  	if @product.save
  		flash[:success]= "Photo Created"
  		redirect_to @product
  	else
  		redirect_to @product
  	end

  end


  def index
    @products = Product.all
    @categories = Category.all
    @sub_categories = SubCategory.all
  end

  def show

  
  end

  def edit
    @product = Product.find(params[:id])
    @categories =Category.all
    @sub_categories = SubCategory.all 


  end
  def update 

    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:success] ="Product Update"
      redirect_to action:"index"
    else
      render 'edit'
    end

  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Product deleted Successful!"
    redirect_to products_path
  end


  private 
  	def product_params
  		params.require(:product).permit(:sku,:user_id, :name, :file, :width, :height, :depth, :category_id, :sub_category_id, :product_order)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		# redirect_to @user = redirect_to user_url(@user)
  		log_in @user
  		flash[:success] = "Welcome to the L & N Office Furniture"
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end 

  private   
  def user_params     
  	params.require(:user).permit(:name, :email,
  :password, :password_confirmation)   
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	#return the full title on a per page basis
	def full_title (page_title= '')
		base_title = " L & N Office System Sdn Bhd"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"

		end
	end
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_sub_categories_helper.rb
module CategorySubCategoriesHelper
end

app/helpers/category_sub_category_helper.rb
module CategorySubCategoryHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


def log_in(user)
	session[:user_id] = user.id
end


def current_user
	@current_user ||= User.find_by(id: session[:user_id])

end


def logged_in?
	!current_user.nil? 
end

def log_out
	session.delete(:user_id)
	@current_user = nil; 
end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/sub__helper.rb
module SubHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/category_sub_categories/edit.html.erb
<div class="row">
	<%= render 'layouts/adminsidebar' %>  
	<div class= "col-md-4">
	</diV>
	<div class= "col-md-4">
		<h2> Add Category-Sub_Category </h2>
		<%= form_for @category_sub_category do |f| %>

	      <%= f.label :category_id, "Category" %>
	      <%= f.collection_select(:category_id, @categories, :id, :title, :include_blank =>" Please select an category") %>
	<!--       <%= f.text_field :category_id , class: 'form-control'%>
	 -->
	      <%= f.label :sub_category_id, "Sub_category" %>
	            <%= f.collection_select(:sub_category_id, @sub_categories, :id, :title, :include_blank =>" Please select an sub-category")%>

	<!--       <%= f.text_field :sub_category_id, class: 'form-control' %>
	 -->
	      <%= f.submit "Save Changes", class: "btn btn-primary" %>
	    <% end %>

	</div>
</div>

app/views/category_sub_categories/index.html.erb
<div class ="row">
<%= render 'layouts/adminsidebar' %>  


<div class= "col-md-10"> 
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Category</th>
        <th>Category name</th>
        <th>Sub_category</th>
        <th>Sub Category name</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% if @category_sub_categories.any? %>
     <% @category_sub_categories.each do |cat| %>
      <tr> 
        <td> <%= cat.category_id %></td>
        <td> <%= cat.category.title %> <td>
        <% if cat.sub_category_id.nil? %>  
          <td>nil</td>
          <td>nil</td>
        <% else %>
          <td> <%= cat.sub_category.title %> </td>
          <td> <%= cat.sub_category_id %> </td>
        <% end %>
        <td><td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_category_sub_category_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>

     <% end %>
     <% end %>
    </tbody>
  </table>

  </div>



</div>

<div class="row">
<div class= "col-md-4">
</diV>
<div class= "col-md-4">
	<h2> Add Category-Sub_Category </h2>
	<%= form_for @category_sub_category do |f| %>

      <%= f.label :category_id, "Category" %>
      <%= f.collection_select(:category_id, @categories, :id, :title, :include_blank =>" Please select an category") %>
<!--       <%= f.text_field :category_id , class: 'form-control'%>
 -->
      <%= f.label :sub_category_id, "Sub_category" %>
            <%= f.collection_select(:sub_category_id, @sub_categories, :id, :title, :include_blank =>" Please select an sub-category")%>

<!--       <%= f.text_field :sub_category_id, class: 'form-control' %>
 -->
      <%= f.submit "Add Category", class: "btn btn-primary" %>
    <% end %>

</div>


</div>