config/routes.rb
Rails.application.routes.draw do
  

  get 'sub_categories/new'
  get 'sub_categories/index'
  get 'sub_categories/show'

  get 'categories/new'
  get 'categories/index'
  get 'categories/show'

  root 'static_pages#home'
  get 'contact' => 'contacts#new'
  get 'product_catalogs'   => 'static_pages#catalog'
  get 'about'     =>  'static_pages#about'
  get 'signup'    =>  'users#new'
  get 'login'      =>  'sessions#new'
  post 'login'      =>  'sessions#create'
  delete 'logout'      =>  'sessions#destroy'
  get 'admin'   =>'users#index'

  get 'categories' =>'categories#index'
  post 'categories' => 'categories#create'
  delete 'categories' => 'categories#destroy'

  get 'sub_categories' => 'sub_categories#index'

  get 'category_sub_categories' => 'category_sub_categories#index'

  get 'add_products' => 'products#new'
  get 'products' => 'products#index'
  post 'products' => 'products#create'
  delete 'products' =>'products#destroy' 

  get 'catalog' => 'catalogs#index'

  get 'users/new'
  resources :users
  resources :products
  resources :categories
  resources :sub_categories
  resources :category_sub_categories
  resources :catalogs
  resource  :contacts, only:[:new, :create]
  

end

app/models/catalog.rb
class Catalog < ActiveRecord::Base

		mount_uploader :file_url, CatalogUploader

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :category_sub_categories
	has_many :sub_categories, :through => :category_sub_categories


end

app/models/category_sub_category.rb
class CategorySubCategory < ActiveRecord::Base

	belongs_to :category
	belongs_to :sub_category
	
end

app/models/contact.rb
class Contact 
	# include ActiveAttr::Validation
	# include ActiveAttr::Conversion
	# include ActiveModel::Naming
	include ::ActiveAttr::Model

	attribute :name
	attribute :email
	attribute :message
	attribute :contact_no

	attr_accessor :name, :email, :message, :contact_no

	validates_presence_of :name
	validates_presence_of :contact_no
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates_presence_of :message, :maximum => 500

	def initialize(attributes ={})
		attributes.each do |name, value|

			send("#{name}=", value)
		end
	end

def persisted?
	false
end

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_one :category
	has_one :sub_category
	mount_uploader :file, ProductUploader

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base

	has_many :category_sub_categories
	has_many :categories, :through => :category_sub_categories

	
end

app/models/user.rb
class User < ActiveRecord::Base

before_save {self.email = email.downcase}

has_many :products
validates :name, presence: true, length: {maximum: 50}

VALID_EMAIL_REGREX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, 
									length:{maximum: 255},
									format: {with: VALID_EMAIL_REGREX},
									uniqueness: { case_sensitive: false}

has_secure_password
validates :password, length: { minimum: 6 }
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController


	def new
		@catalog = Catalog.new
	end

	def index
		@catalog = Catalog.new
		@catalogs = Catalog.all
	end

	def create 
		@catalog = Catalog.create(catalog_params)
		 	if @catalog.save
  		flash[:success]= "Photo Created"
  		redirect_to catalog_path
  	else
  		flash[:danger]= "Photo not created successful"
  		redirect_to catalog_path
  	end

	end

	def show
	end

	def delete
	end

	private
	def catalog_params
		params.require(:catalog).permit(:title, :file_url)
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  

  def new
  	@category =Category.new
  end

  def create 
  	@category = Category.create(category_params)
  	if @category.save
  		flash[:success] = "Cateogry Add Successful"
  		redirect_to categories_path
  	else
	  	redirect_to categories_path
  	end

  end

  def index
  	@categories= Category.all
  	@category = Category.new
  end

  def show

  	@category= Category.find(params[:id])
  	@category_sub_category = CategorySubCategory.where(category_id: @category.id)
  	# byebug
  	# @category_sub_category.each do |cat|
   
  		if @category_sub_category.count == 0 
  			
  			 @products = Product.where(category_id: @category.id).order("product_order ASC")

  		end
  	
  end

  def edit

    @category =Category.find(params[:id])
  end

  def update 

    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] ="Category Update"
      redirect_to action:"index"
    else
      render 'edit'
    end

  end


  def destroy
  	Category.find(params[:id]).destroy
  	flash[:success] = "Category deleted Successful!"
  	redirect_to categories_path
  end


  private 
  	def category_params
  		params.require(:category).permit(:title, :description)
  	end 
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


	def new
		@contact = Contact.new
	end
	


	def create
		@contact = Contact.new(params[:contact])
		if @contact.valid?
			#TO do send message here
			flash[:success]= "Thank you sending us the enquiry!"
			ContactusMailer.quotation_notification(@contact).deliver

			redirect_to contact_path
		else 
			flash[:danger]= "unsuccessful"
			redirect_to contact_path

		end
	end 	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new

  	@product = Product.new
  	@categories =Category.all
  	@sub_categories = SubCategory.all 
  end

  def create

  	@product = current_user.products.build(product_params)
  	
  	if @product.save
  		flash[:success]= "Photo Created"
  		redirect_to @product
  	else
  		redirect_to @product
  	end

  end


  def index
    @products = Product.all
    @categories = Category.all
    @sub_categories = SubCategory.all
  end

  def show

  
  end

  def edit
    @product = Product.find(params[:id])
    @categories =Category.all
    @sub_categories = SubCategory.all 


  end
  def update 

    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:success] ="Product Update"
      redirect_to action:"index"
    else
      render 'edit'
    end

  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Product deleted Successful!"
    redirect_to products_path
  end


  private 
  	def product_params
  		params.require(:product).permit(:sku,:user_id, :name, :file, :width, :height, :depth, :category_id, :sub_category_id, :product_order)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])		
  		#log the user in and redirect to the user's show page.
  		log_in user
  		redirect_to "/admin"   #will change it later on. 
  	else
  		#create an error message. 
  		flash[:danger]="Invalid email/password combination"
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	redirect_to root_path 

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		# redirect_to @user = redirect_to user_url(@user)
  		log_in @user
  		flash[:success] = "Welcome to the L & N Office Furniture"
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end 

  private   
  def user_params     
  	params.require(:user).permit(:name, :email,
  :password, :password_confirmation)   
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	#return the full title on a per page basis
	def full_title (page_title= '')
		base_title = " L & N Office System Sdn Bhd"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"

		end
	end
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


def log_in(user)
	session[:user_id] = user.id
end


def current_user
	@current_user ||= User.find_by(id: session[:user_id])

end


def logged_in?
	!current_user.nil? 
end

def log_out
	session.delete(:user_id)
	@current_user = nil; 
end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/sub__helper.rb
module SubHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/catalogs/index.html.erb
<div class="row">

  <%= render 'layouts/adminsidebar' %>
  <div class= "col-md-10"> 
    <h2> Product Catalog Listing </h2>

     <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    <% if @catalogs.any? %>
     <% @catalogs.each do |catalog| %>
      <tr>
        <td><%= catalog.title %></td>
        <td><%= catalog.file_url %></td>
        <td><td><%= link_to 'Show', catalog %></td>
        <td><%= link_to 'Edit', '#' %></td>
        <td><%= link_to 'Destroy', catalog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     <% end %>
     <% end %>
    </tbody>
  </table>


  </div>
  <div class="col-md-4">
   <%= form_for @catalog, :html => {:multipart => true} do |f| %>
      <%= f.label :title, "File Name to display: " %>
      <%= f.text_field :title , class: 'form-control'%>

      <%= f.label :file_url, "Upload File" %>
      <%= f.file_field :file_url %> 

      <%= f.submit "Add File", class: "btn btn-primary" %>


      <% end %>
    </div>

</div>

app/views/categories/edit.html.erb
<div class ="row">
<%= render 'layouts/adminsidebar' %>  

<div class= "col-md-4">
</diV>
<div class= "col-md-4">
	<h2> Edit Category </h2>
	<%= form_for @category do |f| %>

      <%= f.label :title, "Title" %>
      <%= f.text_field :title , class: 'form-control'%>

      <%= f.label :description, "Description" %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.submit "Save Changes", class: "btn btn-primary" %>
    <% end %>

</div>


</div>

app/views/categories/index.html.erb
<div class ="row">
<%= render 'layouts/adminsidebar' %>  


<div class= "col-md-10"> 
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
     <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <td><td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     <% end %>
    </tbody>
  </table>

  </div>



</div>

<div class="row">
<div class= "col-md-4">
</diV>
<div class= "col-md-4">
	<h2> Add Category </h2>
	<%= form_for @category do |f| %>

      <%= f.label :title, "Title" %>
      <%= f.text_field :title , class: 'form-control'%>

      <%= f.label :description, "Description" %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.submit "Add Category", class: "btn btn-primary" %>
    <% end %>

</div>


</div>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

<div class="row">
<% if @category_sub_category.count == 0%>

<% @products.each do |product| %>

		<div class= "col-md-3 pro-img-holder"> 

			 <div class="pro-img"><%= link_to image_tag(product.file, size:"230x300", alt: "L&N Office System"), '#' %> </div>
			 <div class="pro-desc">
			 <p><strong> <%= product.sku %> </strong>
		 	 <% if product.name %> 
		 	 <strong><%= product.name%> </strong></br>
		 	 <% end %>
			<%= product.height%> </br>
			<%= product.width%> </br>
			<%= product.depth%></p> 
		</div>
		</div>
	<% end %>
<% else %>
	<% @category_sub_category.each do |sub| %>
		<% sub_products = Product.where(sub_category_id: sub.sub_category_id).order("product_order ASC") %>
			<% sub_category = SubCategory.find(sub.sub_category_id) %>
			<h3> <%= sub_category.title %> </h3>
			<hr/>
		
			<% sub_products.each do |product| %> 

				<div class="col-md-3 pro-img-holder">
				
				<div class="pro-img"><%= link_to image_tag(product.file, size:"230x300", alt: "L&N Office System"), '#' %>	</div>
					<div class="pro-desc">
						<p><strong> <%= product.sku %> </strong> </br>
						 <% if product.name %> 	
	 	 					<strong><%= product.name%> </strong> </br>
	 					 <% end %>
					<%= product.height%> </br>
					<%= product.width%> </br>
					<%= product.depth%> 	</p>	
 					</div>
		
				</div>
			
			<% end %>
			</br></br></br>
	<% end %>

<% end %>
</div>

app/views/contacts/new.html.erb
<% provide(:title, "Contact Us") %> 

<div class="jumbotron jumbotron-sm">
  <div class = "container">
  <div class="row">
    

    <div class = "col-md-6">
      <form>
            <legend><span class="glyphicon glyphicon-globe"></span> Our office</legend>
            <address>
                <strong>Office & Factory </strong><br>
                 Lot 2775B, Kg Baru Sg. Buloh, <br>
                  47000 Sungai Buloh, Selangor D. E., Malaysia <br>
                <abbr title="Phone">
                    Tel:</abbr>
                  603-6156 3340 / 3527 <br>
                 <abbr title="Fax">
                    Fax:</abbr>
                  603-6157 8171 <br>
                  <abbr title="Email">lnoffsys@gmail.com </abbr>

            </address>
       <!--      <address>
                <strong>Full Name</strong><br>
                <a href="mailto:#">first.last@example.com</a>
            </address> -->
            </form>

    </div>



  <div class="col-md-6">

    <legend><span class="glyphicon glyphicon-user"></span> Contact Us</legend>
   <%= form_for @contact, :html => {:multipart => true} do |f| %>

   <% if @contact.errors.any? %>
    <div class="error_message"> 
      <h2> <%= pluralize(@contact.errors.count, "Error") %> Prohibited this message been send </h2>
      <ul> 
        <% @contact.errors.full_messages.each do |msg| %>

        <li> <%= msg %></li>
        <% end %> 

      </ul>
    </div>
      
    <% end %>
      <%= f.label :name, "Name" %>
      <%= f.text_field :name , class: 'form-control'%>

      <%= f.label :email, "Email" %>
      <%= f.text_field :email, class: 'form-control' %>
      <%= f.label :contact_no, "Contact Number" %>
      <%= f.text_field :contact_no, class: 'form-control' %>

      <%= f.label :message, "Message" %>
      <%= f.text_area :message, class: 'form-control' %>

      <%= f.submit "Ask for Quotation", class: "btn btn-primary" %>


      <% end %>
    </div>

  </div>
</div>
</div>

app/views/products/edit.html.erb
<div class="row">
  <h2> Edit Products </h2>
  <%= render 'layouts/adminsidebar' %>
  <div class="col-md-4">
   <%= form_for @product, :html => {:multipart => true} do |f| %>
      
      <%= f.label :product_order, "Product Order in Category:" %>
      <%= f.text_field :product_order , class: 'form-control'%>
      
      <%= f.label :sku, "Product SKU" %>
      <%= f.text_field :sku , class: 'form-control'%>


      <%= f.label :name, "Name" %>
      <%= f.text_field :name , class: 'form-control'%>
       <%= f.label :height, "Height" %>
      <%= f.text_field :height, class: 'form-control' %>
      <%= f.label :width, "Width" %>
      <%= f.text_field :width, class: 'form-control' %>

     
      <%= f.label :depth, "Depth" %>
      <%= f.text_field :depth, class: 'form-control' %>

      <%= f.label :category_id, "Category" %>
      <%= f.collection_select(:category_id, @categories, :id, :title, :include_blank =>" Please select an category") %>

      <%= f.label :sub_category_id, "Sub_category" %>
            <%= f.collection_select(:sub_category_id, @sub_categories, :id, :title, :include_blank =>" Please select an sub-category")%>
      <%= f.label :file, "Upload Image" %>
      <%= f.file_field :file %> 

      <%= f.submit "Update", class: "btn btn-primary" %>


      <% end %>
    </div>

</div>

app/views/products/index.html.erb
<div class ="row">
<%= render 'layouts/adminsidebar' %>  


<div class= "col-md-10"> 
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Product SKU</th>
        <th>Name</th>
        
        <th>Category Name </th>
        <th>Sub Category Name </th>
<!--         <th>Picture URL </th>
 -->        <th>Action</th>
      </tr>
    </thead>
    <tbody>
     <% @products.each do |product| %>
      <tr>
        <td><%= product.sku %></td>
        <td><%= product.name %></td>
        <% if product.category_id %>
        <% category = Category.find(product.category_id) %>
        <td><%= category.title%> </td>
          <% else %>
           <td>No category </td>
          <% end %>
        <% if product.sub_category_id %>
          <% sub_category = SubCategory.find(product.sub_category_id) %>
          <td><%= sub_category.title %> </td>
          <% else %>
            <td>No sub-category</td>
            <% end %>

        <td><td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
     <% end %>
    </tbody>
  </table>

  </div>

app/views/users/index.html.erb
<div class ="row">
<%= render 'layouts/adminsidebar' %>  

<div class= "col-md-10"> 
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>John</td>
        <td>Doe</td>
        <td>john@example.com</td>
      </tr>
      <tr>
        <td>Mary</td>
        <td>Moe</td>
        <td>mary@example.com</td>
      </tr>
      <tr>
        <td>July</td>
        <td>Dooley</td>
        <td>july@example.com</td>
      </tr>
    </tbody>
  </table>

  </div>


</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    	<%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name , class: 'form-control'%>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class ="row">
   <div class="col-md-2">
    <ul class="nav nav-pills nav-stacked">
      <li class="active"><a href="#">Home</a></li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Menu 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Submenu 1-1</a></li>
          <li><a href="#">Submenu 1-2</a></li>
          <li><a href="#">Submenu 1-3</a></li>                        
        </ul>
      </li>
      <li><a href="#">Menu 2</a></li>
      <li><a href="#">Menu 3</a></li>
    </ul>
  </div>
  <div class="clearfix visible-lg"></div>
  <div class= "col-md-10"> 
    

  </div>
</div>