config/routes.rb
Rails.application.routes.draw do
  

  get 'sub_categories/new'
  get 'sub_categories/index'
  get 'sub_categories/show'

  get 'categories/new'
  get 'categories/index'
  get 'categories/show'

  root 'static_pages#home'
  get 'contact' => 'contacts#new'
  get 'product_catalogs'   => 'static_pages#catalog'
  get 'about'     =>  'static_pages#about'
  get 'signup'    =>  'users#new'
  get 'login'      =>  'sessions#new'
  post 'login'      =>  'sessions#create'
  delete 'logout'      =>  'sessions#destroy'
  get 'admin'   =>'users#index'

  get 'categories' =>'categories#index'
  post 'categories' => 'categories#create'
  delete 'categories' => 'categories#destroy'

  get 'sub_categories' => 'sub_categories#index'

  get 'category_sub_categories' => 'category_sub_categories#index'

  get 'add_products' => 'products#new'
  get 'products' => 'products#index'
  post 'products' => 'products#create'
  delete 'products' =>'products#destroy' 

  get 'catalog' => 'catalogs#index'

  get 'users/new'
  resources :users
  resources :products
  resources :categories
  resources :sub_categories
  resources :category_sub_categories
  resources :catalogs
  resource  :contacts, only:[:new, :create]
  

end

app/models/catalog.rb
class Catalog < ActiveRecord::Base

		mount_uploader :file_url, CatalogUploader

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :category_sub_categories
	has_many :sub_categories, :through => :category_sub_categories


end

app/models/category_sub_category.rb
class CategorySubCategory < ActiveRecord::Base

	belongs_to :category
	belongs_to :sub_category
	
end

app/models/contact.rb
class Contact 
	# include ActiveAttr::Validation
	# include ActiveAttr::Conversion
	# include ActiveModel::Naming
	include ::ActiveAttr::Model

	attribute :name
	attribute :email
	attribute :message
	attribute :contact_no

	attr_accessor :name, :email, :message, :contact_no

	validates_presence_of :name
	validates_presence_of :contact_no
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validates_presence_of :message, :maximum => 500

	def initialize(attributes ={})
		attributes.each do |name, value|

			send("#{name}=", value)
		end
	end

def persisted?
	false
end

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_one :category
	has_one :sub_category
	mount_uploader :file, ProductUploader

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base

	has_many :category_sub_categories
	has_many :categories, :through => :category_sub_categories

	
end

app/models/user.rb
class User < ActiveRecord::Base

before_save {self.email = email.downcase}

has_many :products
validates :name, presence: true, length: {maximum: 50}

VALID_EMAIL_REGREX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, 
									length:{maximum: 255},
									format: {with: VALID_EMAIL_REGREX},
									uniqueness: { case_sensitive: false}

has_secure_password
validates :password, length: { minimum: 6 }
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController


	def new
		@catalog = Catalog.new
	end

	def index
		@catalog = Catalog.new
		@catalogs = Catalog.all
	end

	def create 
		@catalog = Catalog.create(catalog_params)
		 	if @catalog.save
  		flash[:success]= "Photo Created"
  		redirect_to catalog_path
  	else
  		flash[:danger]= "Photo not created successful"
  		redirect_to catalog_path
  	end

	end

	def show
	end

	def delete
	end

	private
	def catalog_params
		params.require(:catalog).permit(:title, :file_url)
	end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


	def new
		@contact = Contact.new
	end
	


	def create
		@contact = Contact.new(params[:contact])
		if @contact.valid?
			#TO do send message here
			flash[:success]= "Thank you sending us the enquiry!"
			ContactusMailer.quotation_notification(@contact).deliver

			redirect_to contact_path
		else 
			flash[:danger]= "unsuccessful"
			redirect_to contact_path

		end
	end 	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		# redirect_to @user = redirect_to user_url(@user)
  		log_in @user
  		flash[:success] = "Welcome to the L & N Office Furniture"
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end 

  private   
  def user_params     
  	params.require(:user).permit(:name, :email,
  :password, :password_confirmation)   
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	#return the full title on a per page basis
	def full_title (page_title= '')
		base_title = " L & N Office System Sdn Bhd"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"

		end
	end
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


def log_in(user)
	session[:user_id] = user.id
end


def current_user
	@current_user ||= User.find_by(id: session[:user_id])

end


def logged_in?
	!current_user.nil? 
end

def log_out
	session.delete(:user_id)
	@current_user = nil; 
end



end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/sub__helper.rb
module SubHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_adminsidebar.html.erb
<div class="col-md-2">
  <ul class="nav nav-pills nav-stacked">
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#"> Product <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Add Product",add_products_path %></li>
        <li><%= link_to "Product Listing", products_path %></li>       
        <li><a href="#">Submenu 1-3</a></li>                        
      </ul>
    </li>
    <li><%= link_to "Add Category", categories_path %></li>
    <li><%= link_to "Add Sub-Category", sub_categories_path %></li>
    <li><%= link_to "Add Category_Sub_Category", category_sub_categories_path %></li>
    <li><%= link_to "Add Product Catalogs", catalogs_path %></li>
  </ul>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small> 
		<p>Copyright &copy L & N Office Furniture Sdn Bhd 2015. All Right Reserved</p>
	</small>
	<nav> 
		<ul>  
			<li><%= link_to "About", about_path%></li>
			 <li><%= link_to "Product Catalog", product_catalogs_path%></li>
			 <li><%= link_to "Contact", contact_path %></li>
		</ul>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default"> 
	<div class="container"> 
		<%= link_to "sample app",root_path, id: "logo" %>
		<nav> 
			<ul class="nav navbar-nav navbar-left"> 
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Product Catalog", product_catalogs_path %></li>
		
				<li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Products
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
          	<% Category.order('title ASC').each do|category| %>
            <li><%= link_to category.title, category %></li>
           <% end %>
          
          </ul>
        </li>
        <li><%= link_to "Contact", contact_path %></li>
			</ul> 
			<ul class="nav navbar-nav navbar-right">
				<%if logged_in? %>
				<li><%= link_to "Logout", logout_path, method:"delete" %></li>
				<% else %> 
				<li><%= link_to "Admin Login", login_path %></li>
				<%end %>
			</ul> 
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 <%= render 'layouts/shim' %>
</head>
<body>
	 <%= render 'layouts/header' %>
	<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
	<div class="container"> 
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>


</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_photo_form.html.erb
<%= form_for(@product) do |f| %>
<!--   <input type="hidden" name="referrer" value="LABEL" />
  <input type="hidden" id="callback_url" name="exit" value="https://label-fashionistas.herokuapp.com/photos" />
  <input type="hidden" name="method" value="GET" />
  <input type="hidden" name="target" value="https://label-fashionistas.herokuapp.com/photos/pixlr" />
  <input type="hidden" name="locktarget" value="true" />
  <input type="hidden" name="locktitle" value="true" />
  <input type="hidden" name="locktype" value="jpg" />
  <input type="hidden" name="quality" value="100" />
 -->
 
  <div class="title">

  </div>
  <div id="picture">
    <div class="wrapper">
      <%= f.file_field :file, class: "file-upload" %>
      
    </div>
    <button disabled>Add Photo</button>
  </div>
  <div>
    <label id="file-name"></label>
  </div>
  <p class="less_topspaced">
    <input id="snipshot" type="checkbox" style="border:0;" />
    <label for="snipshot" class="normal">&nbsp; I want to <b>edit</b>, <b>rotate</b>, or <b>crop</b> my photo first.</label>
  </p>
  <div>
    <%= f.submit "Post", class: "btn btn-primary" %>
  </div>
<% end %>